Quandela/Perceval

.github/workflows/autotests.yml, setup.py
+ Upgrade quandelibc min version to 0.5.3
=> Export packages lib.*.predefined

perceval/rendering/canvas/svg_canvas.py
which can zoom in or out the circuit drawing
=> PCVL-177 + PCVL-175: fix SvgCanvas

.github/workflows/autotests.yml
this has to be on main branch to allow github action variable input
please squash this PR
=> enable autotests input

.github/workflows/autotests.yml
=> autotests - choose quandelibc version

perceval/backends/mps.py, perceval/backends/template.py
(caused by all fockstates having a separate_state method)
=> Fix computation slow down

perceval/algorithm/sampler.py, perceval/backends/cliffords2017.py, perceval/components/abstract_processor.py, perceval/components/processor.py, scripts/local_computation.py, tests/test_converter_qiskit.py
Processor sampling methods return two types of performance:
- perf on mode detection: the number of modes with at least 1 photon has a lower threshold
- perf on postprocess: the rate of having a valid output state regarding heralds and post process function
=> PCVL-232 Processor post select on modes with photon(s)

perceval/algorithm/analyzer.py
Fix an issue in Analyzer dealing with probs returning sometimes basic states, sometimes state vectors
=> Fix issue in Analyzer

perceval/backends/template.py, perceval/rendering/pdisplay.py, perceval/utils/statevector.py, tests/test_serialization.py, tests/test_source.py, tests/test_statevector.py
* Fix StateVector and SVDistribution normalization at display (without changing internal data)
* SVDistribution forces normalization before sampling
=> PCVL-223 StateVector and SVD display & normalization

perceval/runtime/remote_processor.py
Avoid remote commands to be sent when some simple constraints do not match
=> PCVL-240 Worker compatibility checks on mode and photon count

perceval/backends/slos.py, perceval/utils/statevector.py, tests/test_simulators.py
test_simulators.py now tests all_prob
disable SLOS-specific all_prob optimization
=> PCVL-341 SLOS all_prob issue

perceval/serialization/serialize.py, tests/test_serialization.py
In Dictionary and List serializers:
* compression now transfer "compress" parameter
* behavior may differ given the serialized object type
=> Serial compression is more versatile

perceval/utils/qmath.py, perceval/utils/statevector.py, tests/test_qmath.py
Just fixing pow and not using pow from exqalibur
=> Pcvl-484 fix pow

perceval/backends/__init__.py, tests/test_mask.py
fix #PCVL-511 and add test case
=> PCVL-511: access to slos masking

perceval/utils/algorithms/circuit_optimizer.py
=> PCVL-513 fixed circuit_optimizer

perceval/providers/__init__.py, perceval/providers/quandela/__init__.py, perceval/providers/quandela/quandela_session.py, perceval/runtime/remote_processor.py, perceval/runtime/rpc_handler.py, perceval/runtime/session.py, tests/test_circuit.py
Code tested with the following script:
```python
from perceval.providers.quandela import QuandelaSession
from perceval import BS, BasicState, RemoteProcessor
from perceval.algorithm import Sampler
token = "YOUR_TOKEN"
with_session = True
if with_session:
session = QuandelaSession("sim:ascella", token)
p = session.build_remote_processor()
else:
p = RemoteProcessor("sim:ascella", token)
p.add(0, BS())
p.with_input(BasicState([1, 0]))
sampler = Sampler(p)
res = sampler.sample_count(500000)
print(res['results'])
print(res['physical_perf'])
```
=> PCVL-582 multi-provider

.github/workflows/autotests.yml, .github/workflows/benchmarks.yml, .github/workflows/build-and-deploy-docs.yml, .github/workflows/python-publish.yml, .github/workflows/rerun-notebooks-and-build-docs.yml
(cherry picked from commit 1ceff48eba7bb28773b1bf64fce6da7f8de10162)
=> Update github actions from v2 to v4 (#290)

.github/workflows/build-and-deploy-docs.yml, .github/workflows/rerun-notebooks-and-build-docs.yml, docs/requirements.txt, docs/source/conf.py
Changes:
- update sphinx multiversion
- update `config.py` according to the new package
=> change config

README.md
Spotted a few minor misses on the readme while working on the plugin , thought would send a pr to fix it .
=> Minor spell checks (it happens)

docs/source/conf.py
=> filter alpha,beta.. for docs

perceval/rendering/circuit/renderer.py, tests/imgs/test_svg_dump_circuit_box_bell_stateFFF.svg, tests/imgs/test_svg_dump_circuit_box_bell_stateFFT.svg, tests/imgs/test_svg_dump_circuit_box_bell_stateFTF.svg, tests/imgs/test_svg_dump_circuit_box_bell_stateFTT.svg, tests/imgs/test_svg_dump_circuit_box_bell_stateTFF.svg, tests/imgs/test_svg_dump_circuit_box_bell_stateTFT.svg, tests/imgs/test_svg_dump_circuit_box_bell_stateTTF.svg, tests/imgs/test_svg_dump_circuit_box_bell_stateTTT.svg, tests/test_visualization.py
Setting recursive=False in the inner loop of circuit rendering seems to fix the issue, txt pdf and html files are generated correctly and contain the correct circuit of proper size.
files generated for the circuit mentioned in the original issue are here:
https://drive.google.com/drive/folders/1E1cF_RRrfD8HEcfvpSkX1at810IYkHhl?usp=sharing
=> fix for issue Rendering: incorrect size of circuit box #414

.pre-commit-config.yaml, perceval/algorithm/sampler.py, perceval/backends/_abstract_backends.py, perceval/backends/_slos.py, perceval/components/abstract_processor.py, perceval/components/feed_forward_configurator.py, perceval/components/processor.py, perceval/simulators/_simulate_detectors.py, perceval/simulators/feed_forward_simulator.py, perceval/simulators/simulator.py, perceval/simulators/simulator_factory.py, perceval/simulators/simulator_interface.py, perceval/simulators/stepper.py, perceval/utils/__init__.py, perceval/utils/postselect.py, perceval/utils/progress_cb.py, tests/test_ff_configurator.py, tests/test_ff_simulator.py, tests/test_simulator.py
Creation of the new feed-forward simulator.
The feed-forward map configurator class serves as an example of configurator.
This PR does not include specific interactions between Processor and FFConfigurator.
These are not the main topic of the PR and should be better implemented in another PR.[https://github.com/Quandela/Perceval/pull/481](url)
=> Pcvl 800 1st feed forward simulator

perceval/components/processor.py, perceval/simulators/delay_simulator.py, perceval/simulators/feed_forward_simulator.py, perceval/simulators/loss_simulator.py, perceval/simulators/polarization_simulator.py, perceval/simulators/simulator.py, perceval/simulators/simulator_factory.py, perceval/simulators/simulator_interface.py, perceval/simulators/stepper.py, tests/test_loss_channel.py
Also includes this fix on TD simulator
=> Pcvl 824 fix lc simulator number of modes
